export const EventTest = {
  _reactName: "onClick",
  _targetInst: null,
  type: "click",
  target:
    "p.MuiTypography-root.MuiTypography-body1.css-1eklul4-MuiTypography-root",
  altKey: false,
  bubbles: true,
  button: 0,
  buttons: 0,
  cancelable: true,
  clientX: 1121,
  clientY: 60,
  ctrlKey: false,
  currentTarget: null,
  defaultPrevented: false,
  detail: 1,
  eventPhase: 3,
  isTrusted: true,
  metaKey: false,
  movementX: 0,
  movementY: 0,
  pageX: 1121,
  pageY: 60,
  relatedTarget: null,
  screenX: 1161,
  screenY: 159,
  shiftKey: false,
  timeStamp: 4340922.799999997,
};
